// frontend/src/utils/exportUtils.js
import jsPDF from 'jspdf';
import { formatProbability } from './formatters';

export const exportResults = (result, fileName) => {
  const dataStr = JSON.stringify(result, null, 2);
  const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);
  
  const exportFileDefaultName = `deepsafe_analysis_${fileName}_${new Date().toISOString().slice(0,10)}.json`;
  
  const linkElement = document.createElement('a');
  linkElement.setAttribute('href', dataUri);
  linkElement.setAttribute('download', exportFileDefaultName);
  linkElement.click();
};

export const downloadPDF = (result, fileName, preview) => {
  const pdf = new jsPDF();
  
  // Header
  pdf.setFontSize(20);
  pdf.setTextColor(30, 64, 175); // Primary color
  pdf.text('DeepSafe Analysis Report', 20, 20);
  
  // Metadata
  pdf.setFontSize(10);
  pdf.setTextColor(100);
  pdf.text(`Generated: ${new Date().toLocaleString()}`, 20, 30);
  pdf.text(`File: ${fileName}`, 20, 37);
  pdf.text(`Request ID: ${result.request_id}`, 20, 44);
  
  // Main verdict
  pdf.setFontSize(16);
  const verdictColor = result.is_likely_deepfake ? [220, 38, 38] : [34, 197, 94];
  pdf.setTextColor(...verdictColor);
  pdf.text(result.is_likely_deepfake ? 'LIKELY AI-GENERATED' : 'LIKELY AUTHENTIC', 20, 60);
  
  // Details
  pdf.setFontSize(12);
  pdf.setTextColor(50);
  pdf.text(`Confidence: ${formatProbability(result.deepfake_probability)}`, 20, 70);
  pdf.text(`Detection Method: ${result.ensemble_method_used || 'Unknown'}`, 20, 77);
  pdf.text(`Models Used: ${result.model_count || 0}`, 20, 84);
  pdf.text(`Analysis Time: ${result.response_time?.toFixed(2) || 0}s`, 20, 91);
  
  // Model results
  if (result.model_results) {
    pdf.setFontSize(14);
    pdf.setTextColor(30, 64, 175);
    pdf.text('Individual Model Results', 20, 110);
    
    pdf.setFontSize(10);
    pdf.setTextColor(50);
    let yPosition = 120;
    
    Object.entries(result.model_results).forEach(([model, res]) => {
      if (!res.error) {
        pdf.text(`${model}: ${res.class?.toUpperCase()} (${formatProbability(res.probability)})`, 25, yPosition);
        yPosition += 7;
      }
    });
  }
  
  // Add image if preview available
  if (preview) {
    try {
      pdf.addImage(preview, 'JPEG', 120, 50, 70, 70);
    } catch (error) {
      console.error('Error adding image to PDF:', error);
    }
  }
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150);
  pdf.text('Generated by DeepSafe - Advanced AI Deepfake Detection', 20, 280);
  
  // Save the PDF
  pdf.save(`deepsafe_report_${fileName}_${new Date().toISOString().slice(0,10)}.pdf`);
};